[project]
name = "Rice_JAX"
version = "0.1.0"
description = "A high-performance implementation of the Rice-N climate-economy model in JAX"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jymkit[algs]>=0.0b1",
    "matplotlib>=3.10.1",
    "optimistix>=0.0.10",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
    "wandb>=0.19.10",
]

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
