[project]
name = "Rice_JAX"
version = "0.1.1"
description = "A high-performance implementation of the Rice-N climate-economy model in JAX"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jaxnasium[algs]>=0.0.23",
    "matplotlib>=3.7.4",
    "optimistix>=0.0.10",
    "pyyaml>=6.0.2",
    "tqdm>=4.67.1",
    "wandb>=0.19.10",
    "tyro",
    "jax[cuda]==0.6.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["rice_jax"]
include-package-data = true

[tool.hatch.build.targets.wheel]
packages = ["rice_jax"]
package-data = {"rice_jax" = ["config_yamls/*.yaml", "config_yamls/*.yml", "region_yamls/**/*.yml", "region_yamls/**/*.yaml"]}

[tool.ruff.lint]
extend-select = ["I"]

[tool.ruff.lint.isort]
combine-as-imports = true
